apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
      tracesToLogs:
        datasourceUid: loki
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: 'service.name', value: 'service' }]
        queries:
          - name: 'Request rate'
            query: 'sum(rate(duration_milliseconds_count{$__tags}[5m]))'
          - name: 'Request latency'
            query: 'histogram_quantile(0.95, sum(rate(duration_milliseconds_bucket{$__tags}[5m])) by (le))'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"trace_id":"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'

  - name: Netdata
    type: prometheus
    access: proxy
    url: http://host.docker.internal:19999/api/v1/allmetrics
    jsonData:
      customQueryParameters: "format=prometheus"
      prometheusType: Prometheus

  - name: ClickHouse
    type: prometheus
    access: proxy
    url: http://clickhouse-exporter:9116/metrics
    jsonData:
      prometheusType: Prometheus